services:
- type: web
  name: ghost
  env: docker
  plan: standard
  autoDeploy: false
  disk:
    name: ghost
    mountPath: /var/lib/ghost/content
    sizeGB: 10
  envVars:
  - key: database__client
    value: mysql
  - key: database__connection__host
    fromService:
      name: mysql-ghost
      type: pserv
      property: host
  - key: database__connection__database
    fromService:
      name: ghost-mysql
      type: pserv
      envVarKey: MYSQL_DATABASE
  - key: database__connection__user
    fromService:
      name: mysql-ghost
      type: pserv
      envVarKey: MYSQL_USER
  - key: database__connection__password
    fromService:
      name: mysql-ghost
      type: pserv
      envVarKey: MYSQL_PASSWORD

- type: pserv
  name: mysql-ghost
  repo: https://github.com/render-examples/mysql.git
  plan: standard
  env: docker
  autoDeploy: false
  disk:
    name: mysql-ghost
    mountPath: /var/lib/mysql
    sizeGB: 10
  envVars:
  - key: MYSQL_DATABASE
    value: ghost
  - key: MYSQL_USER
    value: ghost-db-user
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
